Logging is configured.
================================================= test session starts =================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 6 items / 3 deselected / 3 selected

tests/api/test_api_todo_pixegami.py::test_api_get FAILED                                                         [ 33%]
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id FAILED                                              [ 66%]
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_user_id Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /list-tasks/Test%20User%201 HTTP/11" 200 12
PASSED                                         [100%]

====================================================== FAILURES =======================================================
____________________________________________________ test_api_get _____________________________________________________

    def test_api_get():
>       Logger.info('getting message')
E       TypeError: Logger.info() missing 1 required positional argument: 'msg'

tests\api\test_api_todo_pixegami.py:10: TypeError
_______________________________________________ test_api_get_task_by_id _______________________________________________

    def test_api_get_task_by_id():
>       print(task_id)
E       NameError: name 'task_id' is not defined

tests\api\test_api_todo_pixegami.py:41: NameError
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
=============================================== short test summary info ===============================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_get - TypeError: Logger.info() missing 1 required positional arg...
FAILED tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id - NameError: name 'task_id' is not defined
====================================== 2 failed, 1 passed, 3 deselected in 2.11s ======================================
