Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: allure-pytest-2.13.5, html-4.1.1, html-reporter-0.2.9, metadata-3.1.1
collected 10 items

tests/api/test_api_todo_pixegami.py::test_api_get getting response message

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:13:59 INFO getting response message
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET / HTTP/11" 200 39
{'message': 'Hello World from Todo API'}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "POST /create-task HTTP/11" 405 31
{'detail': 'Method Not Allowed'}
FAILED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type Creating task with invalid data type.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:14:02 INFO Creating task with invalid data type.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "POST /create-task HTTP/11" 405 31
<Response [405]>
{'detail': 'Method Not Allowed'}
FAILED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:14:03 INFO Creating task with missing one of required field.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "POST /create-task HTTP/11" 405 31
<Response [405]>
{'detail': 'Method Not Allowed'}
FAILED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_creationtime SKIPPED (unconditional skip)
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id FAILED
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_user_id Get task by user id: Test User 1

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-08 11:14:03 INFO Get task by user id: Test User 1
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /list-tasks/Test%20User%201 HTTP/11" 200 861
{'tasks': [{'is_done': False, 'content': 'My test content.', 'ttl': 1723120810, 'user_id': 'Test User 1', 'task_id': 'task_c937175d045e4564ae4e0eb2e33e28da', 'created_time': 1723034410}, {'is_done': False, 'content': 'My test content.', 'ttl': 1723117717, 'user_id': 'Test User 1', 'task_id': 'task_883165fcf2854406b47d17dcaf34ea55', 'created_time': 1723031317}, {'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723117711, 'user_id': 'Test User 1', 'task_id': 'task_37bea58ba4764126bf703e9286961b3c', 'created_time': 1723031311}, {'is_done': False, 'content': 'My test content.', 'ttl': 1723117594, 'user_id': 'Test User 1', 'task_id': 'task_af356dfedc9a45b6bd47ce99055ae4fa', 'created_time': 1723031194}, {'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723117589, 'user_id': 'Test User 1', 'task_id': 'task_c193cfca7e2c463ab74c0ccaba1a56db', 'created_time': 1723031189}]}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_update_task FAILED
tests/api/test_api_todo_pixegami.py::test_api_update_task_creation_time SKIPPED (unconditional skip)
tests/api/test_api_todo_pixegami.py::test_api_del_task_by_id FAILED

============================================================= FAILURES =============================================================
_____________________________________________________ test_api_put_create_task _____________________________________________________

    def test_api_put_create_task():
        global task_id
    
        response = HelperClass.create_task(json_payload["create_task_payload"])
        response_data = response.json()
        print(response_data)
>       task_id =  response_data[FrameworkConstant.TASK][FrameworkConstant.TASK_ID]
E       KeyError: 'task'

tests\api\test_api_todo_pixegami.py:37: KeyError
____________________________________________ test_api_put_create_task_invalid_data_type ____________________________________________

    def test_api_put_create_task_invalid_data_type():
    
        Logger.info('Creating task with invalid data type.')
        response = HelperClass.create_task(json_payload["invalid_data_type"])
        print(response)
        response_data = response.json()
        print(response_data)
    
        status_code = response.status_code
>       response_msg = response_data["detail"][0]["msg"]
E       TypeError: string indices must be integers, not 'str'

tests\api\test_api_todo_pixegami.py:56: TypeError
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-08 11:14:02 INFO Creating task with invalid data type.
_________________________________________ test_api_put_create_task_missing_required_field __________________________________________

    def test_api_put_create_task_missing_required_field():
    
        Logger.info('Creating task with missing one of required field.')
        response = HelperClass.create_task(json_payload["missing_required_field"])
        print(response)
        response_data = response.json()
        print(response_data)
    
        status_code = response.status_code
>       response_msg = response_data["detail"][0]["msg"]
E       TypeError: string indices must be integers, not 'str'

tests\api\test_api_todo_pixegami.py:72: TypeError
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-08 11:14:03 INFO Creating task with missing one of required field.
_____________________________________________________ test_api_get_task_by_id ______________________________________________________

    def test_api_get_task_by_id():
>       print(task_id)
E       NameError: name 'task_id' is not defined

tests\api\test_api_todo_pixegami.py:104: NameError
_______________________________________________________ test_api_update_task _______________________________________________________

    def test_api_update_task():
    
>       Logger.info("Update task with id: "+task_id)
E       NameError: name 'task_id' is not defined

tests\api\test_api_todo_pixegami.py:129: NameError
_____________________________________________________ test_api_del_task_by_id ______________________________________________________

    def test_api_del_task_by_id():
>       Logger.info("Delete task with id: "+task_id)
E       NameError: name 'task_id' is not defined

tests\api\test_api_todo_pixegami.py:169: NameError
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task - KeyError: 'task'
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type - TypeError: string indices must be integer...
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field - TypeError: string indices must be in...
FAILED tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id - NameError: name 'task_id' is not defined
FAILED tests/api/test_api_todo_pixegami.py::test_api_update_task - NameError: name 'task_id' is not defined
FAILED tests/api/test_api_todo_pixegami.py::test_api_del_task_by_id - NameError: name 'task_id' is not defined
============================================== 6 failed, 2 passed, 2 skipped in 8.28s ==============================================
