Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 7 items / 6 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_put_create_task_bad_request Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 111
Creating new task with bad request.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 15:44:56 INFO Creating new task with bad request.
FAILED                                                                                                                        [100%]

============================================================= FAILURES =============================================================
_______________________________________________ test_api_put_create_task_bad_request _______________________________________________

    def test_api_put_create_task_bad_request():
        global task_id
        payload = {
            "content": "abc",
            "user_id": 1,
            "is_done": "not done"
        }
        response = HelperClass.create_task(payload)
        print(response)
        response_data = response.json()
        print(response_data)
    
        Logger.info('Creating new task with bad request.')
        status_code = response.status_code
        response_msg = response_data["detail"][0]["msg"]
        response_error_type = response_data["detail"][0]["type"]
        print(response_msg)
        print(status_code)
>       assert FrameworkConstant.INVALID_DATA_TYPE_MSG == response_data
E       AssertionError: assert 'value could not be parsed to a boolean' == {'detail': [{'loc': ['body', 'is_done'], 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}]}
E        +  where 'value could not be parsed to a boolean' = FrameworkConstant.INVALID_DATA_TYPE_MSG

tests\api\test_api_todo_pixegami.py:65: AssertionError
------------------------------------------------------- Captured stdout call -------------------------------------------------------
<Response [422]>
{'detail': [{'loc': ['body', 'is_done'], 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}]}
value could not be parsed to a boolean
422
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-07 15:44:56 INFO Creating new task with bad request.
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task_bad_request - AssertionError: assert 'value could not be pars...
================================================= 1 failed, 6 deselected in 1.85s ==================================================
