Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 9 items / 8 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_update_task FAILED

============================================================= FAILURES =============================================================
_______________________________________________________ test_api_update_task _______________________________________________________

    def test_api_update_task():
    
>       Logger.info("Update task with id: "+task_id)
E       NameError: name 'task_id' is not defined

tests\api\test_api_todo_pixegami.py:129: NameError
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_update_task - NameError: name 'task_id' is not defined
================================================= 1 failed, 8 deselected in 0.72s ==================================================
