Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 9 items / 8 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type [{'content': 'abc', 'user_id': 1, 'is_done': 'not done'}]
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 111
<Response [422]>
{'detail': [{'loc': ['body', 'is_done'], 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}]}
Creating task with invalid data type.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:44:34 INFO Creating task with invalid data type.
value could not be parsed to a boolean
422
PASSED

- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
================================================= 1 passed, 8 deselected in 1.58s ==================================================
