Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: allure-pytest-2.13.5, html-4.1.1, html-reporter-0.2.9, metadata-3.1.1
collected 14 items / 13 deselected / 1 selected

tests/test_flow.py::test_api_task_flow Creating task.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-09 14:32:20 INFO Creating task.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 200
{'task': {'user_id': 'Test User Jaymin', 'content': 'My test content with for Test User New.', 'is_done': False, 'created_time': 1723194142, 'task_id': 'task_5d6b29211ca24b2ea3e1964abcf86783', 'ttl': 1723280542}}
4.257399
FAILED

============================================================= FAILURES =============================================================
________________________________________________________ test_api_task_flow ________________________________________________________

    def test_api_task_flow():
        Logger.info("Creating task.")
        response = HelperClass.create_task(json_payload["create_task_payload"])
        response_data = response.json()
        print(response_data)
        response_time = response.elapsed.total_seconds()
        print(response_time)
>       assert response_time <= FrameworkConstant.MAX_RESPONSE_TIME_CREATE_TASK
E       assert 4.257399 <= 1.9
E        +  where 1.9 = FrameworkConstant.MAX_RESPONSE_TIME_CREATE_TASK

tests\test_flow.py:24: AssertionError
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-09 14:32:20 INFO Creating task.
===================================================== short test summary info ======================================================
FAILED tests/test_flow.py::test_api_task_flow - assert 4.257399 <= 1.9
================================================= 1 failed, 13 deselected in 5.14s =================================================
