Logging is configured.
================================================= test session starts =================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 6 items

tests/api/test_api_todo_pixegami.py::test_api_get getting response message

---------------------------------------------------- live log call ----------------------------------------------------
2024-08-06 12:27:09 INFO getting response message
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET / HTTP/11" 200 39
{'message': 'Hello World from Todo API'}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 172
{'task': {'user_id': 'Test User 1', 'content': 'My test content.', 'is_done': False, 'created_time': 1722927431, 'task_id': 'task_84cd918dc5b1459b8eb80125bfe9cad3', 'ttl': 1723013831}}
task_84cd918dc5b1459b8eb80125bfe9cad3
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id task_84cd918dc5b1459b8eb80125bfe9cad3
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_84cd918dc5b1459b8eb80125bfe9cad3 HTTP/11" 200 163
{'is_done': False, 'content': 'My test content.', 'ttl': 1723013831, 'user_id': 'Test User 1', 'task_id': 'task_84cd918dc5b1459b8eb80125bfe9cad3', 'created_time': 1722927431}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_user_id Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /list-tasks/Test%20User%201 HTTP/11" 200 175
{'tasks': [{'is_done': False, 'content': 'My test content.', 'ttl': 1723013831, 'user_id': 'Test User 1', 'task_id': 'task_84cd918dc5b1459b8eb80125bfe9cad3', 'created_time': 1722927431}]}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_update_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /update-task HTTP/11" 200 31
{'updated_task_id': 'task_id 5'}
200
FAILED
tests/api/test_api_todo_pixegami.py::test_api_del_task_by_id Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "DELETE /delete-task/task_84cd918dc5b1459b8eb80125bfe9cad3 HTTP/11" 200 59
{'deleted_task_id': 'task_84cd918dc5b1459b8eb80125bfe9cad3'}
200
PASSED

====================================================== FAILURES =======================================================
________________________________________________ test_api_update_task _________________________________________________

    def test_api_update_task():
        payload = {
            "content": "Updated content",
            "user_id": "Test user updated",
            "task_id": "task_id 5",
            "is_done": True
        }
        response = HelperClass.update_task(payload)
        response_data = response.json()
        print(response_data)
    
        status_code = response.status_code
        print(status_code)
>       assert task_id == response_data["updated_task_id"]
E       AssertionError: assert 'task_84cd918...80125bfe9cad3' == 'task_id 5'
E         
E         - task_id 5
E         + task_84cd918dc5b1459b8eb80125bfe9cad3

tests\api\test_api_todo_pixegami.py:82: AssertionError
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
=============================================== short test summary info ===============================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_update_task - AssertionError: assert 'task_84cd918...80125bfe9ca...
============================================= 1 failed, 5 passed in 7.34s =============================================
