Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 9 items / 5 deselected / 4 selected

tests/api/test_api_todo_pixegami.py::test_api_put_create_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 187
{'task': {'user_id': 'Test User 1', 'content': 'My test content with json file.', 'is_done': False, 'created_time': 1723031311, 'task_id': 'task_37bea58ba4764126bf703e9286961b3c', 'ttl': 1723117711}}
task_37bea58ba4764126bf703e9286961b3c
Creating new task with id: task_37bea58ba4764126bf703e9286961b3c

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:18:34 INFO Creating new task with id: task_37bea58ba4764126bf703e9286961b3c
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 111
<Response [422]>
{'detail': [{'loc': ['body', 'is_done'], 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}]}
Creating task with invalid data type.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:18:35 INFO Creating task with invalid data type.
value could not be parsed to a boolean
422
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 91
<Response [422]>
{'detail': [{'loc': ['body', 'content'], 'msg': 'field required', 'type': 'value_error.missing'}]}
Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:18:36 INFO Creating task with missing one of required field.
field required
422
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_creationtime Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 172
<Response [200]>
{'task': {'user_id': 'Test User 1', 'content': 'My test content.', 'is_done': False, 'created_time': 1723031317, 'task_id': 'task_883165fcf2854406b47d17dcaf34ea55', 'ttl': 1723117717}}
Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:18:37 INFO Creating task with missing one of required field.
FAILED

============================================================= FAILURES =============================================================
__________________________________________ test_api_put_create_task_invalid_creationtime ___________________________________________

    def test_api_put_create_task_invalid_creationtime():
        global task_id
        payload = {
            "content": "My test content.",
            "user_id": "Test User 1",
            "task_id": "task_id 5",
            "is_done": False,
            "created_time": 7-8-2024
        }
        response = HelperClass.create_task(payload)
        print(response)
        response_data = response.json()
        print(response_data)
    
        Logger.info('Creating task with missing one of required field.')
        status_code = response.status_code
>       response_msg = response_data["detail"][0]["msg"]
E       KeyError: 'detail'

tests\api\test_api_todo_pixegami.py:104: KeyError
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-07 17:18:37 INFO Creating task with missing one of required field.
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_creationtime - KeyError: 'detail'
============================================ 1 failed, 3 passed, 5 deselected in 8.07s =============================================
